# wonka documentation rules and instructions

# Project Information

site_name: wonka
site_description: Extensible, lightweight, accessible constructors
site_url: https://WithPrecedent.github.io/wonka
# site_dir: "site"
repo_name: WithPrecedent/wonka
repo_url: https://github.com/WithPrecedent/wonka
# edit_uri: blob/main/docs/
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/wonka]
copyright: Copyright &copy; 2023 Corey Rayburn Yung
docs_dir: docs

# Documentation Structure

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- User Guide:
  - Design: design.md
  - Recipes: recipes.md
- API: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage Report: coverage.md

# Documentation Appearance

theme:
  name: material
  logo: img/top_hat.png
  locale: en
  icon:
    repo: fontawesome/brands/github
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: lighht)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  # use_directory_urls: false

# Extras, Extensions, and Plugins

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- attr_list
- admonition
- callouts
- codehilite
- footnotes
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tasklist:
    custom_checkbox: true
- sane_lists
- toc:
    permalink: true

plugins:
- autorefs
- coverage:
    page_name: coverage
    html_report_dir: htmlcov
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
# - git-committers:
#     enabled: !ENV [DEPLOY, false]
#     repository: WithPrecedent/wonka
- literate-nav:
    nav_file: SUMMARY.md
- markdown-exec:
- minify:
    minify_html: !ENV [DEPLOY, false]
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_section_style: table
          filters:
            - "!^__"
          heading_level: 1
          # members_order: alphabetical
          merge_init_into_class: true
          separate_signature: false
          show_signature_annotations: false
          # show_submodules: true
# - render_swagger:
#     title: API Reference        
- search:

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/WithPrecedent
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/wonka/
